### ISSUE TITLE
[Bug] sageattn3_blackwell: CUDA error: misaligned address on RTX 5060 Ti (Blackwell)

### ISSUE THREAD

**Issue by gzsiang** [thu-ml/SageAttention#357]
## Bug Description
When using `sageattn3_blackwell` mode on RTX 5060 Ti (Blackwell architecture), it throws "CUDA error: misaligned address" error during inference.

## Environment
- **OS:** Windows 11
- **GPU:** NVIDIA RTX 5060 Ti 16GB (Blackwell architecture, sm_120)
- **Python:** 3.14.0
- **PyTorch:** 2.12.0.dev20260318+cu130
- **CUDA:** 13.0
- **SageAttention3:** Latest code from GitHub (fresh clone and compile)

## Steps to Reproduce
1. Clone SageAttention3 repository from GitHub
2. Compile with Visual Studio 2022 19.44 (added `-allow-unsupported-compiler` flag to nvcc_flags)
3. Install with `pip install -e .`
4. Use `sageattn3_blackwell` mode in ComfyUI with Patch Sage Attention node
5. Run inference

## Expected Behavior
Attention computation should work without CUDA errors.

## Actual Behavior
```
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```

## Additional Context
- SageAttention 2.2 works fine on the same system
- The issue appears to be specific to the Blackwell kernel implementation in SageAttention3
- Fresh compilation from latest GitHub code does not resolve the issue
- Related to existing issues #270 and #148 about Blackwell support

## Notes
I have successfully compiled SageAttention3 after adding `-allow-unsupported-compiler` flag to handle Visual Studio version compatibility, but the runtime misaligned address error persists. This suggests the issue is in the Blackwell kernel code itself rather than a compilation problem.

**Comment by woct0rdho** [comment]
You may try the fork at https://github.com/mengqin/SageAttention , and see the discussion at https://github.com/thu-ml/SageAttention/pull/323

**Comment by gzsiang** [comment]
@woct0rdho 非常感谢你的帮助！

按照你推荐的 mengqin/SageAttention fork 成功编译并运行了。具体步骤：

1. 克隆 https://github.com/mengqin/SageAttention
2. 在 sageattention3_blackwell/setup.py 的 Windows 分支添加 -allow-unsupported-compiler 以支持 VS 2022
3. 使用 pip install --no-build-isolation -e . 安装

环境：Windows 11 + RTX 5060 Ti (Blackwell sm_120) + Python 3.14 + PyTorch 2.12.0.dev+cu130

之前遇到的 CUDA error: misaligned address 完全解决了，sageattn3_blackwell 可以正常运行。

不过实际测试中发现性能提升有限（在 Lumina2 和 HunyuanVideo 上对比 sageattn_qk_int8_pv_fp8_cuda++），可能是因为 torch.compile 的 graph break 或者这个修复方式引入了额外的内存分配开销。但无论如何，能跑起来就是胜利！

再次感谢！

**Comment by bfreshour** [comment]
> You may try the fork at https://github.com/mengqin/SageAttention , and see the discussion at [#323](https://github.com/thu-ml/SageAttention/pull/323)

This fork also worked for me as I was also getting the same misaligned address issue on a 5070TI.
